cache:
  # - node_modules
  - '%USERPROFILE%\.electron'
environment:
  GH_TOKEN:
      secure: GG3j7UxXlamSiVI3UGBEQ9SXYylyne6A/WRn4Q2JrGCdcmCtNMd3f3XU7vWlM+gV
  matrix:
    - nodejs_version: 11
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - npm install --save-dev electron-rebuild
matrix:
  fast_finish: true
version: '{build}'
shallow_clone: true
clone_depth: 1
image: Visual Studio 2017
platform:
  - x64
init:
  - git config --global core.autocrlf input
build_script:
  - .\node_modules\.bin\electron-rebuild.cmd
  - npm run build
test: true
before_deploy:
  - npm run electron-builder
deploy:
  - provider: GitHub
    auth_token:
      secure: GG3j7UxXlamSiVI3UGBEQ9SXYylyne6A/WRn4Q2JrGCdcmCtNMd3f3XU7vWlM+gV
    draft: true
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true